[tools]
darklua = "seaofvoices/darklua@0.13.0"
rojo = "rojo-rbx/rojo@7.4.1"
lune = "lune-org/lune@0.8.3"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"
wally = "UpliftGames/wally@0.3.2"
asphalt = "jacktabscode/asphalt@0.4.2"
